model_config:

  input_channels: 2
  n_stages: 5
  features_per_stage: [32, 64, 128, 256, 512]
  kernel_sizes: [3, 3, 3, 3, 3]
  strides: [1, 2, 2, 2, 2]
  n_conv_per_stage: [2, 2, 2, 1, 1]
  num_classes: 4
  n_conv_per_stage_decoder: [2, 2, 1, 1]
  deep_supervision: false

